POST http://localhost:3001/doctors/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhvc3AxYWRtaW4iLCJpYXQiOjE2MTI3MTIxMTZ9.lz4jjGy_x_XiHyTcX5RRzv2N8GVLFPoCHn1lTO2dtGo
Role: admin

{
  "firstName": "abc",
  "lastName": "xyz",
  "hospitalId": 1,
  "speciality": "versatile"
}

###
PATCH http://localhost:3001/patients/PID1/grant/HOSP2-DOC1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBJRDAiLCJpYXQiOjE2MTI3NDU5MTF9.K0-7Zlv5JZOyXQMjX6Mn4d4f56JAV_MwZ_Q9D8m5ec8
Role: patient

###
GET http://localhost:3001/doctors/1/_all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBJRDEiLCJpYXQiOjE2MTI4MDMwNTF9.wD8eGfmm-V2JIDiQ-GsCGv_A-DlvbRFlhiYItMHXrSY
Role: doctor
Username: PID1

###
GET http://localhost:3001/patients/PID3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhPU1AxLURPQzUiLCJpYXQiOjE2MTI4MjQwOTN9.NJhAkgzGl7nIHeanZKKcReK15RXWNcVQv2kaoPIjT4o
Role: doctor
Username: PID3